global_costmap:
  global_frame: world
  robot_base_frame: chassis_link
  update_frequency: 5.0
  publish_frequency: 5.0
  # static_map: true
  resolution: 0.1
  transform_tolerance: 0.5
  plugins:
    - {name: static_layer,            type: "costmap_2d::StaticLayer"}
    - {name: obstacle_layer,          type: "costmap_2d::VoxelLayer"}
    - {name: inflation_layer, type: "costmap_2d::InflationLayer", 
     inflation_radius: 0.4, cost_scaling_factor: 3.0}




