local_costmap:
  global_frame: world
  robot_base_frame: chassis_link
  update_frequency: 5.0
  publish_frequency: 5.0
  # static_map: false
  rolling_window: true
  width: 3.0
  height: 3.0
  resolution: 0.05
  transform_tolerance: 0.5

  plugins:
   - {name: static_layer,        type: "costmap_2d::StaticLayer"}
   - {name: obstacle_layer,      type: "costmap_2d::ObstacleLayer"}
   - {name: inflation_layer, type: "costmap_2d::InflationLayer", 
     inflation_radius: 0.25, cost_scaling_factor: 5.0}
